import Head from "next/head";
import { useRouter } from "next/router";
import axios from "axios";
import { useState, useEffect } from "react";
import Link from "next/link";
import Footer from "../components/Footer";
import withAuth from "../components/Auth";
import useSWR, { mutate } from "swr";
import AdminNav from "../components/AdminNav";

const URL = `http://localhost/api/gallery`;
const fetcher = (url) => axios.get(url).then((res) => res.data);

const AdminGallery = ({ token }) => {
  const router = useRouter();

  const [image, setImage] = useState([]);
  const [src, setSrc] = useState("");

  const { data, error } = useSWR(URL, fetcher);
  if (!data) {
    return (
      <div className="flex justify-center items-center h-screen w-full">
        Loading...
      </div>
    );
  }

  const addImage = async (src) => {
    await axios.post(URL, { src });
    mutate(URL);
  };

  const deleteImage = async (id) => {
    await axios.delete(`${URL}/${id}`);
    mutate(URL);
  };

  return (
    <>
      <Head>
        <title>Management - by Chamook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo-b.svg" />
      </Head>
      <AdminNav />
      <div className="w-full min-h-screen h-full bg-black flex justify-center p-5 relative overflow-hidden">
        <div className="max-w-7xl w-full p-1 z-10">
          <section className="w-full flex flex-col justify-center items-center gap-5 p-3">
            <p className="text-white font-normal text-2xl">จัดการรูปภาพ</p>
          </section>

          <section className="bg-white rounded-lg my-2 w-full h-full">
            <div className="p-10 ">
              <div className="inline-flex w-full justify-center items-center">
                <p className="mr-4"> Image link </p>

                <input
                  className="appearance-none bg-transparent border-b border-teal-500  text-black    py-1 px-2 leading-tight focus:outline-none font-light w-96 mr-4 "
                  type="text"
                  id="imageSrc"
                  placeholder="ใส่ url รูปภาพ"
                  onChange={(e) => setSrc(e.target.value)}
                />
                <div>
                  <button
                    onClick={() => addImage(src)}
                    className="bg-green-600 px-5 py-2 w-fit rounded-md text-white"
                  >
                    เพิ่มรูปภาพ
                  </button>
                </div>
              </div>
            </div>
            <div className="p-10">
              <div className="grid grid-cols-5 gap-1 w-full">
                {data.map((item, index) => (
                  <div key={index} className="w-52 h-52 relative">
                    <div className="overflow-hidden absolute w-full h-full">
                      <img
                        src={item.src}
                        alt="gallery"
                        className="object-cover w-full h-full"
                      />
                    </div>
                    <div className="absolute w-full h-full flex items-end justify-center ">
                      <button
                        onClick={() => deleteImage(item.id)}
                        className="bg-red-500 px-5 w-fit py-2 mb-2 rounded text-white"
                      >
                        ลบรูปภาพ
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </section>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default withAuth(AdminGallery);

export function getServerSideProps({ req, res }) {
  return { props: { token: req.cookies.token || "" } };
}
