import Head from "next/head";
import { useRouter } from "next/router";
import axios from "axios";
import { useState, useEffect } from "react";
import Link from "next/link";
import Footer from "../components/Footer";

const Blog = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Blog - by Chamook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo-b.svg" />
      </Head>
      <div className="w-full min-h-screen h-full bg-black flex justify-center p-5 relative overflow-hidden">
        <div className="max-w-7xl w-full p-1 z-10">
          <div className="w-full flex justify-between">
            <button
              onClick={() => router.push("/")}
              className="bg-transparent  text-white inline-flex items-center justify-center"
            >
              <svg
                className="w-5 h-5 mr-2 -ml-1 rotate-180"
                aria-hidden="true"
                focusable="false"
                data-prefix="fab"
                data-icon="apple"
                role="img"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 256 512"
              >
                <path
                  fill="currentColor"
                  d="M64 448c-8.188 0-16.38-3.125-22.62-9.375c-12.5-12.5-12.5-32.75 0-45.25L178.8 256L41.38 118.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25l-160 160C80.38 444.9 72.19 448 64 448z"
                />
              </svg>
              กลับหน้าแรก
            </button>
            <Link href="/login">
              <button className="border-2 border-white text-white px-2 py-1 hover:bg-white hover:text-black">
                ลงชื่อเข้าใช้
              </button>
            </Link>
          </div>

          <section className="w-full flex flex-col justify-center items-center gap-5 p-3">
            <p className="text-white font-normal text-2xl">
              บทความเกี่ยวกับแมว
            </p>
            <div className="w-full grid grid-cols-1 sm:grid-cols-2  md:grid-cols-4 gap-2">
              <div className="max-h-[450px] w-full  h-full rounded-lg overflow-hidden ">
                <div className="grid w-full h-full grid-cols-1 gap-2 bg-white justify-items-center ">
                  <img
                    src="/assets/gallery/gallery1.png"
                    alt="card11"
                    className="w-full h-full object-cover"
                  />
                  <div className="overflow-hidden p-2">
                    <p>เรื่องควรรู้ของทาสแมว...มือใหม่ !!</p>
                    <p className="text-sm font-light">
                      แมว เป็นสัตว์ที่รักอิสระ ที่มีความน่ารัก ขี้เล่น
                      และเป็นสัตว์ที่รักความสะอาด
                      ดังนั้นแมวจึงเป็นสัตว์เลี้ยงยอดนิยมที่คนเลือกนำมาเลี้ยง
                      และจำเป็นต้องได้รับการดูแลอย่างเหมาะสมสำหรับผู้เลี้ยงแมวมือใหม่
                      ก่อนที่จะทำการเลือกแมวมาเลี้ยงนั้น
                      สิ่งแรกที่คุณต้องตัดสินใจไม่ใช่ว่าจะเลือกตัวไหนมาเลี้ยงดี
                      แต่ต้องติดสินใจว่าคุณเหมาะสมที่จะเลี้ยงแมวหรือไม่
                      โดยคำนึงถึงปัจจัยหลาย ๆ อย่าง เช่น
                      การให้เวลาเลี้ยงดูเจ้าแมวเหมียว การให้อาหาร
                      การทำความสะอาดกระบะทราย รวมทั้งค่าใช้จ่ายต่าง ๆ เป็นต้น..
                    </p>
                  </div>
                  <div className="py-2">
                    <Link href="https://www.yippeehappy.com/th/blog/detail/774/%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%87%E0%B8%84%E0%B8%A7%E0%B8%A3%E0%B8%A3%E0%B8%B9%E0%B9%89%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%97%E0%B8%B2%E0%B8%AA%E0%B9%81%E0%B8%A1%E0%B8%A7-%E0%B8%A1%E0%B8%B7%E0%B8%AD%E0%B9%83%E0%B8%AB%E0%B8%A1%E0%B9%88">
                      <button className="border-2 border-black text-black px-2 py-1 hover:bg-black hover:text-white w-fit">
                        อ่านเพิ่มเติม
                      </button>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Blog;
