import Head from "next/head";
import { useRouter } from "next/router";
import axios from "axios";
import { useState, useEffect } from "react";
import Link from "next/link";
import Footer from "../components/Footer";
import { Fancybox } from "@fancyapps/ui";

const Gallery = () => {
  const router = useRouter();
  useEffect(() => {
    Fancybox.bind('[data-fancybox="gallery"]', {
      Toolbar: {
        display: [
          { id: "zoom", position: "left" },
          { id: "download", position: "left" },
          { id: "counter", position: "center" },
          { id: "close", position: "right" },
        ],
      },
    });
  }, []);
  return (
    <>
      <Head>
        <title>Gallery - by Chamook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo-b.svg" />
      </Head>
      <div className="w-full min-h-screen h-full bg-black flex justify-center p-5 relative overflow-hidden">
        <div className="max-w-7xl w-full p-1 z-10">
          <div className="w-full flex justify-between">
            <button
              onClick={() => router.push("/")}
              className="bg-transparent  text-white inline-flex items-center justify-center"
            >
              <svg
                className="w-5 h-5 mr-2 -ml-1 rotate-180"
                aria-hidden="true"
                focusable="false"
                data-prefix="fab"
                data-icon="apple"
                role="img"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 256 512"
              >
                <path
                  fill="currentColor"
                  d="M64 448c-8.188 0-16.38-3.125-22.62-9.375c-12.5-12.5-12.5-32.75 0-45.25L178.8 256L41.38 118.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25l-160 160C80.38 444.9 72.19 448 64 448z"
                />
              </svg>
              กลับหน้าแรก
            </button>
            <Link href="/login">
              <button className="border-2 border-white text-white px-2 py-1 hover:bg-white hover:text-black">
                ลงชื่อเข้าใช้
              </button>
            </Link>
          </div>

          <section className="w-full flex flex-col justify-center items-center gap-5 p-3">
            <p className="text-white font-normal text-2xl">แกลอรี่ แมวๆ</p>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3 w-full">
              <div className="rounded-lg overflow-hidden">
                <a
                  href="/assets/gallery/gallery1.png"
                  data-fancybox="gallery"
                  data-download-src="/assets/gallery/gallery1.png"
                >
                  <img
                    src="/assets/gallery/gallery1.png"
                    alt="gallery1"
                    className="object-cover w-full h-full object-center hover:scale-110 duration-200"
                  />
                </a>
              </div>
              <div className="rounded-lg overflow-hidden">
                <a
                  href="/assets/gallery/gallery2.png"
                  data-fancybox="gallery"
                  data-download-src="/assets/gallery/gallery2.png"
                >
                  <img
                    src="/assets/gallery/gallery2.png"
                    alt="gallery2"
                    className="object-cover w-full h-full object-center hover:scale-110 duration-200"
                  />
                </a>
              </div>
              <div className="rounded-lg overflow-hidden">
                <a
                  href="/assets/gallery/gallery3.png"
                  data-fancybox="gallery"
                  data-download-src="/assets/gallery/gallery3.png"
                >
                  <img
                    src="/assets/gallery/gallery3.png"
                    alt="gallery3"
                    className="object-cover w-full h-full object-center hover:scale-110 duration-200"
                  />
                </a>
              </div>
              <div className="rounded-lg overflow-hidden">
                <a
                  href="/assets/gallery/gallery4.png"
                  data-fancybox="gallery"
                  data-download-src="/assets/gallery/gallery4.png"
                >
                  <img
                    src="/assets/gallery/gallery4.png"
                    alt="gallery4"
                    className="object-cover w-full h-full object-center hover:scale-110 duration-200"
                  />
                </a>
              </div>
              <div className="rounded-lg overflow-hidden">
                <a
                  href="/assets/gallery/gallery5.png"
                  data-fancybox="gallery"
                  data-download-src="/assets/gallery/gallery5.png"
                >
                  <img
                    src="/assets/gallery/gallery5.png"
                    alt="gallery5"
                    className="object-cover w-full h-full object-center hover:scale-110 duration-200"
                  />
                </a>
              </div>
              <div className="rounded-lg overflow-hidden">
                <a
                  href="/assets/gallery/gallery6.png"
                  data-fancybox="gallery"
                  data-download-src="/assets/gallery/gallery6.png"
                >
                  <img
                    src="/assets/gallery/gallery6.png"
                    alt="gallery6"
                    className="object-cover w-full h-full object-center hover:scale-110 duration-200"
                  />
                </a>
              </div>
              <div className="rounded-lg overflow-hidden">
                <a
                  href="/assets/gallery/gallery7.png"
                  data-fancybox="gallery"
                  data-download-src="/assets/gallery/gallery7.png"
                >
                  <img
                    src="/assets/gallery/gallery7.png"
                    alt="gallery7"
                    className="object-cover w-full h-full object-center hover:scale-110 duration-200"
                  />
                </a>
              </div>
              <div className="rounded-lg overflow-hidden">
                <a
                  href="/assets/gallery/gallery8.png"
                  data-fancybox="gallery"
                  data-download-src="/assets/gallery/gallery8.png"
                >
                  <img
                    src="/assets/gallery/gallery8.png"
                    alt="gallery8"
                    className="object-cover w-full h-full object-center hover:scale-110 duration-200"
                  />
                </a>
              </div>
              <div className="rounded-lg overflow-hidden">
                <a
                  href="/assets/gallery/gallery9.png"
                  data-fancybox="gallery"
                  data-download-src="/assets/gallery/gallery9.png"
                >
                  <img
                    src="/assets/gallery/gallery9.png"
                    alt="gallery9"
                    className="object-cover w-full h-full object-center hover:scale-110 duration-200"
                  />
                </a>
              </div>
            </div>
          </section>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Gallery;
