import Head from "next/head";
import Image from "next/image";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import React from "react";
import useSound from "use-sound";
import Link from "next/link";

export default function Home() {
  const [play] = useSound("/Cute-cat-effect.mp3");

  return (
    <>
      <Head>
        <title>Cat School - by Chamook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo-b.svg" />
      </Head>

      <main>
        <Nav />
        <div
          id="head"
          className="min-h-screen min-w-full w-full h-full bg-[url('/assets/wepik-2022311-2361.png')] bg-cover bg-no-repeat bg-center relative"
        >
          <div className="max-w-7xl w-full h-full flex justify-end p-1 items-center absolute">
            <button
              className="border-2 p-2 w-48 border-white text-white "
              onClick={play}
            >
              Click Me
            </button>
          </div>
        </div>

        <div
          id="section1"
          className="w-full h-full bg-black flex justify-center p-5"
        >
          <div className="max-w-7xl w-full p-1 ">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="w-full h-72 bg-white rounded-md relative overflow-hidden">
                <img
                  src="/assets/card1.png"
                  alt="card1"
                  className="object-cover object-left-top w-full h-full hover:scale-110 transition-transform duration-100 absolute"
                />
              </div>
              <div className="w-full h-72 bg-white rounded-md relative overflow-hidden">
                <img
                  src="/assets/card2.png"
                  alt="card2"
                  className="object-cover w-full h-full hover:scale-110 transition-transform duration-100 absolute"
                />
              </div>

              <div className="w-full h-72 bg-white rounded-md relative overflow-hidden">
                <img
                  src="/assets/card3.png"
                  alt="card3"
                  className="object-cover object-right-top w-full h-full hover:scale-110 transition-transform duration-100 absolute"
                />
              </div>
            </div>

            <div
              id="section2"
              className="h-min overflow-hidden flex flex-col md:flex-row w-full relative "
            >
              <img
                src="/assets/wepik-2022311-23542.png"
                alt="blackcat"
                className="object-contain h-[500px] object-left "
              />

              <div className="p-5 text-white w-full h-auto flex flex-col justify-center  relative ">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi,
                libero modi pariatur accusantium odio debitis cupiditate tempora
                dolorum dolores corporis odit recusandae voluptas cumque
                laudantium magnam illo nisi perferendis iure.
                <div className="py-5">
                  <button className="border-2 p-2 w-48 border-white text-white hover:bg-white hover:text-black ">
                    อ่านเพิ่มเติม
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div
          id="section3"
          className="w-full h-full bg-black flex justify-center p-5"
        >
          <div className="max-w-7xl w-full p-1">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="w-full h-72 bg-white rounded-md relative overflow-hidden">
                <img
                  src="/assets/gallery1.png"
                  alt="card1"
                  className="object-cover object-left-top w-full h-full hover:scale-110 transition-transform duration-100 absolute"
                />
              </div>
              <div className="w-full h-72 bg-white rounded-md relative overflow-hidden">
                <img
                  src="/assets/gallery2.png"
                  alt="card2"
                  className="object-cover w-full h-full hover:scale-110 transition-transform duration-100 absolute"
                />
              </div>

              <div className="w-full h-72 bg-white rounded-md relative overflow-hidden">
                <img
                  src="/assets/gallery3.png"
                  alt="card3"
                  className="object-cover object-right-top w-full h-full hover:scale-110 transition-transform duration-100 absolute"
                />
              </div>
            </div>

            <div className="w-full flex justify-center pt-5">
              <Link href="/gallery">
                <button className="border-2 p-2 w-48 border-white text-white hover:bg-white hover:text-black ">
                  View Gallery
                </button>
              </Link>
            </div>
          </div>
        </div>

        <div
          id="section4"
          className="w-full h-full bg-white flex justify-center p-5"
        >
          <div className="max-w-7xl w-full p-1">
            <div className="h-min overflow-hidden flex flex-col md:flex-row w-full relative ">
              <div className="p-5 text-black w-full h-auto flex justify-center flex-col relative ">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi,
                libero modi pariatur accusantium odio debitis cupiditate tempora
                dolorum dolores corporis odit recusandae voluptas cumque
                laudantium magnam illo nisi perferendis iure.
                <div className="py-5">
                  <button className="border-2 p-2 w-48 border-black text-black hover:bg-black hover:text-white ">
                    อ่านเพิ่มเติม
                  </button>
                </div>
              </div>
              <img
                src="/assets/wepik-2022312-0925.png"
                alt="blackcat"
                className="object-contain h-[500px] object-right "
              />
            </div>
          </div>
        </div>

        <Footer />
      </main>
    </>
  );
}
