import Head from "next/head";
import { useRouter } from "next/router";
import axios from "axios";
import { useState, useEffect } from "react";
import Link from "next/link";
import Footer from "../components/Footer";

const URL = `http://localhost/api/cats`;

const Specialcats = () => {
  const [cats, setCats] = useState([]);

  const router = useRouter();

  useEffect(() => {
    getCats();
  }, []);

  const getCats = async () => {
    return await axios.get(URL).then((res) => {
      if (res.data) {
        setCats(res.data);
      }
    });
  };

  return (
    <>
      <Head>
        <title>แมวสายพันธุ์แปลกๆ - by Chamook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo-b.svg" />
      </Head>
      <div className="w-full min-h-screen h-full bg-black flex justify-center p-5 relative overflow-hidden">
        <div className="max-w-7xl w-full p-1 z-10">
          <div className="w-full flex justify-between">
            <button
              onClick={() => router.push("/")}
              className="bg-transparent  text-white inline-flex items-center justify-center"
            >
              <svg
                className="w-5 h-5 mr-2 -ml-1 rotate-180"
                aria-hidden="true"
                focusable="false"
                data-prefix="fab"
                data-icon="apple"
                role="img"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 256 512"
              >
                <path
                  fill="currentColor"
                  d="M64 448c-8.188 0-16.38-3.125-22.62-9.375c-12.5-12.5-12.5-32.75 0-45.25L178.8 256L41.38 118.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25l-160 160C80.38 444.9 72.19 448 64 448z"
                />
              </svg>
              กลับหน้าแรก
            </button>
            <Link href="/login">
              <button className="border-2 border-white text-white px-2 py-1 hover:bg-white hover:text-black">
                ลงชื่อเข้าใช้
              </button>
            </Link>
          </div>

          <section className="w-full flex flex-col justify-center items-center gap-5 p-3">
            <p className="text-white font-normal text-2xl">แมวสายพันธุ์แปลกๆ</p>
            <div className="grid grid-cols-1 gap-3 min-h-[500px] h-full w-4/5">
              {cats
                .filter((p) => p.type == "special")
                .map((item, index) => (
                  <div
                    key={index}
                    className="grid grid-cols-2 bg-white rounded p-5"
                  >
                    <div className="flex justify-center">
                      <img
                        src={item.image}
                        alt="cattai"
                        className="w-96 h-96 object-contain object-center"
                      />
                    </div>
                    <div className="flex flex-col">
                      <p className="text-xl mb-2">
                        สายพันธุ์:
                        <span className="ml-4 font-medium">{item.name}</span>
                      </p>
                      <p className="text-xl mb-2">
                        อธิบาย:
                        <span className="ml-4 font-light text-base">
                          {item.description}
                        </span>
                      </p>
                      <p className="text-xl mb-2">
                        ลักษณะนิสัย:
                        <span className="ml-4 font-light text-base">
                          {item.character}
                        </span>
                      </p>
                      <p className="text-xl mb-2">
                        การเลี้ยงดู:
                        <span className="ml-4 font-light text-base">
                          {item.treatment}
                        </span>
                      </p>
                    </div>
                  </div>
                ))}
            </div>
          </section>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Specialcats;
